version: "3"
services:
    #  volumes:
    #    database_volumes:
    #      external: true
    #      name: [ volume-name ]

  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_DATABASE: userdb
      #      MYSQL_USER: user
      #      MYSQL_PASSWORD: userpwd
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpwd
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    expose:
      - "3303"
    #    volumes:
    #      - ./backups:/home/backups
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3303:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  application:
    container_name: application
    env_file:
      .env
    image: studygit/pocketpt:latest
    # image: 042973332120.dkr.ecr.ap-northeast-2.amazonaws.com/pocket-pt:latest
    depends_on:
      - mysql-db
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always