version: "3"
services:
  application:
    container_name: application
    env_file:
      .env.prod
    build: ./pocketpt
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always
