version: "3"
services:
  application:
    container_name: application
    env_file:
      .env.prod
    image: vivian0304/prod-pocket-pt:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always
