version: "3"
services:
  #  volumes:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  application:
    container_name: application
    env_file:
      .env.prod
    build: ./pocketpt
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always

