#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['application:8080']

global:
  scrape_interval: 10s # 10초 마다 Metric을 Pulling
  evaluation_interval: 10s # rule 을 얼마나 빈번하게 검증하는지 설정
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus' # Application prometheus endpoint
    static_configs:
      - targets: ['10.0.120.24:8080', '10.0.220.234:8080'] # Application host:port
