profiles:
  default: local

spring:
  datasource:
    #    include:
    #      #      - docker
    #      - local
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    #    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${SPRING_SECURITY_KAKAO_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_KAKAO_CLIENT_SECRET}
            redirect-uri: ${SPRING_SECURITY_KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
          naver:
            scope: name, email, nickname, mobile
            client-id: ${SPRING_SECURITY_NAVER_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_NAVER_CLIENT_SECRET}
            client-name: Naver
            redirect-uri: ${SPRING_SECURITY_NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          kakao:
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
      resourceserver:

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

cors:
  frontend:${CORS_FRONTEND}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      url: ${AWS_S3_BUCKET_URL}
    region: ${AWS_S3_REGION}
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    stack:
      auto: 'false'

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8000/main
      - https://frontend.pocketpt.shop/main
