# This is a basic workflow to help you get started with Actions
name: haha

on: [workflow_dispatch]

jobs:
  live-deploy:
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: cd pocketpt && chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: cd pocketpt && /.gradlew build
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip ./build/libs/* appspec.yml deploy.sh
        shell: bash
