name: haha

on: [workflow_dispatch]


jobs:
  live-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: cd backend-repo && chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: cd backend-repo && /.gradlew build
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip ./build/libs/* appspec.yml deploy.sh
        shell: bash
            
