name: gitleaks
on: [workflow_dispatch]

jobs:
  live-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
