# This is a basic workflow to help you get started with Actions
name: Build and Deploy Spring Boot to AWS EC2

on: [workflow_dispatch]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: pocket-pt

jobs:
  live-deploy:
    if: contains(github.ref, 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: 
          cd pocketpt
          chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: 
          cd pocketpt
          /.gradlew build
        shell: bash

#       - name: Make zip file
#         run: zip -qq -r ./$GITHUB_SHA.zip ./build/libs/* appspec.yml deploy.sh
#         shell: bash
